# Generated by Django 4.1 on 2024-05-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['title'], 'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
    ]
